### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by torarnv** [Vector35/workflow_objc#45]
Is it enough to install the plugin via the instructions, or do I also need to uncheck this?

<img width="349" alt="image" src="https://user-images.githubusercontent.com/7536/207871727-f11afac9-7026-4f31-be49-68670d56cc1a.png">

**Comment by psifertex** [comment]
The plugin is shipped by default and enabled by default. You have to set it as the default workflow (use open with options or change your settings). The only reason you would uncheck that box is if you wanted to build a modified copy of the plugin and use that version of the plugin instead which would require you to disable the built in one. 

Does that answer your question?

**Comment by torarnv** [comment]
Yes, thank you. I wanted to use the one I built and installed myself. So if I uncheck that, the one I built and installed will get picked up automatically? That's great if so :)

**Comment by psifertex** [comment]
Yup! Just disable the built-in one and put the new one in your [user plugin folder](https://docs.binary.ninja/guide/index.html#user-folder) (also Tools/Plugins/Open Plugin folder).
